### ISSUE TITLE
InvalidOperation

### ISSUE THREAD

**Issue by redbinkieresearchlabs** [antosubash/ThemeChange#1]
Hello Mate,

Thanks for the excellent tutorial. When i download and run your code, it runs perfectly. When i follow the instructions and attempt it on my project, i get the below error in both Identity and Web when I run. Build doesnt show any errors.

An unhandled exception occurred while processing the request.
InvalidOperationException: The layout view '~/Themes/Basic/Layouts/Application.cshtml' could not be located. The following locations were searched:
~/Themes/Basic/Layouts/Application.cshtml
Microsoft.AspNetCore.Mvc.Razor.RazorView.GetLayoutPage(ViewContext context, string executingFilePath, string layoutPath)

Previously i used to have a theme folder in both Identity and Web projects and used to modify the theme files accordingly (using the volo basic nuget package) but I know that is not the right way to do it as its not modularised. Any assistance on this error is highly appreciated.

Regards,
Asrar

**Comment by redbinkieresearchlabs** [comment]
I noticed that there were duplicate ItemGroup sections in the project file which were both referring to all the nuget packages. I removed it and it is running fine now

**Comment by saYRam** [comment]
> I noticed that there were duplicate ItemGroup sections in the project file which were both referring to all the nuget packages. I removed it and it is running fine now

im getting same error. i dont undestood what you meant. which project's ItemGroup you are talking bout?

**Comment by redbinkieresearchlabs** [comment]
> > I noticed that there were duplicate ItemGroup sections in the project file which were both referring to all the nuget packages. I removed it and it is running fine now
> 
> im getting same error. i dont undestood what you meant. which project's ItemGroup you are talking bout?

Open your project file in an editor, verify all the ItemGroup and you will notice there are duplicate entries. Remove the duplicate entries and save the project file and reload the project. That solved it for me.
